- name: awscli config
  expect:
       command: aws configure
       responses:
           AWS Access Key ID: "{{AWS_ACCESS_KEY_ID}}"
           AWS Secret Access Key: "{{AWS_SECRET_ACCESS_KEY}}"
           Default region name: "{{AWS_DEFAUlT_REGION}}"
           Default output format: "json"
